server:
  port: 8080

management:
  health:
    redis:
      enabled: ${spinnaker.redis.enabled}

spinnaker:
  redis:
    enabled: true
    host: localhost
    port: 6379

swagger:
  enabled: true
  title: Spinnaker Front50 API
  description:
  contact:
  patterns:
    - /default/.*
    - /credentials.*
    - /global/.*
    - /notifications.*
    - /pipelines.*
    - /strategies.*
    - /v2/.*
