server:
  port: 8080

spinnaker:
  cassandra:
    enabled: true
    embedded: true
    cluster: CASS_SPINNAKER
    keyspace: front50
    name: default
  redis:
    enabled: false

swagger:
  enabled: true
  title: Spinnaker Front50 API
  description:
  contact:
  patterns:
    - /default/.*
    - /credentials.*
    - /global/.*
    - /notifications.*
    - /pipelines.*
    - /strategies.*
    - /v2/.*
