server:
  port: 8080

management:
  health:
    redis:
      enabled: ${spinnaker.redis.enabled}

cassandra:
  enabled: true

spinnaker:
  cassandra:
    enabled: true
    embedded: true
    cluster: CASS_SPINNAKER
    keyspace: front50
    name: default
  redis:
    enabled: false
    host: localhost
    port: 6379

swagger:
  enabled: true
  title: Spinnaker Front50 API
  description:
  contact:
  patterns:
    - /default/.*
    - /credentials.*
    - /global/.*
    - /notifications.*
    - /pipelines.*
    - /strategies.*
    - /v2/.*
