FROM alpine:3.11
MAINTAINER sig-platform@spinnaker.io
COPY front50-web/build/install/front50 /opt/front50
RUN apk --no-cache add --update bash openjdk11-jre
RUN adduser -D -S spinnaker
RUN mkdir -p /opt/spinnaker/plugins && chown -R spinnaker:nogroup /opt/spinnaker/plugins
USER spinnaker
CMD ["/opt/front50/bin/front50"]
