FROM openjdk:8-jre-alpine

MAINTAINER delivery-engineering@netflix.com

COPY ./front50-web/build/install/front50 /opt/front50

RUN apk --nocache add --update bash

RUN useradd -m spinnaker -U

USER spinnaker

CMD ["/opt/front50/bin/front50"]
